### ISSUE TITLE
Light version of Allium?

### ISSUE THREAD

**Issue by Indianajaune** [hugeblank/allium-cc#16]
Basically this suggestion is to make chat recorder peripheral optionnal so Allium could be used with Computercraft without any ad-ons and still offers some functionality though more limited than with chat recorder.

I don't know how that would work plugin side, maybe a boolean value to tell Allium if the plugin requires chat recorder or not. It could also be made Allium side when loading a plugin, if it requires a chat recorder peripheral it skips the loading of the plugin.

In concrete this would work as an API for command computers to modify how the game behave without the chat functionalities.

**Comment by hugeblank** [comment]
I'm not sure I understand what you want? Could you clarify more what you'd want to do with Allium minus the chat functionality?

**Comment by roger109z** [comment]
I think he wants you to intercept chat messages without the chat recorder?

**Comment by Indianajaune** [comment]
I apologize for not being clear, my idea is that you could still run allium even if there is no Chat Recorder module so commands would work only on the computer running Allium and with obviously less possibilities but it would still allow to control the overall world behavior in one command computer.

One concrete example i have in mind is for a gladiator arena in hadcore, normally you would not be able to be gamemode survival when dying in hardcore but in this case areas would be defined as PVP ground, any player entering as a gladiator it would get a tag or something to identify it as a combattant, when dying they would be teleported to a respawn zone tied to the PVP ground. 

I would be glad to work on this plugin if Allium supported working with no chat recorder.

**Comment by hugeblank** [comment]
Ah okay I see what you're saying, I'll get to implementing it!

**Comment by Indianajaune** [comment]
I could contribute but i am not an advanced lua programmer nor do i know how Allium is built.
Still if you make some instructions or give ways or ideas how this could be implemented, i could work on it.

**Comment by hugeblank** [comment]
Instead of outright erroring, a warning is presented making mention that a chat module was not found. While this means that chat is not captured, internal `chat_capture` events can be queued, and if used with a command, Allium will react in the same manner.

Completed in unstable branch (5eaac4a25799e6027c853227af2c53f2bd2e04af), will be merged to master at some point in the future.
